[build]
  command = "pnpm run build:2023"
  functions = "netlify/functions"
  publish = "years/2023/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF years/2023 services/mail-queue"

[dev]
  command = "pnpm run dev:2023"
